name: github-script

on:
  pull_request:
    branches:
      - main

jobs:
  github-script:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment to PR
        uses: actions/github-script@v5
        with:
          script: |
            const output = '123\n101112'
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

